
server:
   port: 10088
   servlet:
      context-path: /czyj_ny


spring:
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
   datasource:
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: jfgl
      password: jfgl
      driver-class-name: oracle.jdbc.OracleDriver
   resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
   thymeleaf:
      cache: false
      prefix:
         classpath: /templates/ # 访问template下的html文件需要配置模板，映射
      suffix: .html
      encoding: utf-8
      mode: HTML5
      servlet:
         content-type: text/html

mybatis:
   mapper-locations: classpath*:mapper/**/*.xml
   type-aliases-package: com.zckj.demo.bean
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: oracle #自动检测当前的数据库链接，自动选择合适的分页方式 也即说明方言为oracle
  reasonable: true   #对页码小于0的时候有帮助
  support-methods-arguments: true
  params: count=countSql